In [21]:
import numpy as np

In [22]:
np.__version__

'2.3.5'

In [23]:
my_list=[0,1,2,3,4]

In [24]:
my_list

[0, 1, 2, 3, 4]

In [25]:
type(my_list)

list

In [26]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4])

In [27]:
type(arr)

numpy.ndarray

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [30]:
np.arange(10,20,5)

array([10, 15])

In [31]:
np.arange(10,20,5,2)

TypeError: Cannot interpret '2' as a data type

In [ ]:
np.zeros(5)                          # Parameter Tuning

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5, dtype=int)              # Hyperparameter Tunung

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros([2,2], dtype=int)

array([[0, 0],
       [0, 0]])

In [ ]:
np.zeros([5,10],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones([3,5], dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones([3,5])


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.arange(20,10)

array([], dtype=int64)

In [ ]:
np.arange(10,20)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(-20,10)


array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [ ]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.threes(3)

AttributeError: module 'numpy' has no attribute 'threes'

In [ ]:
random.rand(3,2)

NameError: name 'random' is not defined

In [ ]:
np.random.rand(2)

array([0.54179842, 0.13996473])

In [ ]:
np.random.rand(5)


array([0.27390761, 0.16610205, 0.15696547, 0.74302395, 0.14974427])

In [ ]:
np.random.rand(3,2)


array([[0.05389024, 0.34795138],
       [0.45456235, 0.759943  ],
       [0.09479558, 0.33822588]])

In [ ]:
np.random.randint(3)


2

In [ ]:
np.random.randint(5,10)

7

In [ ]:
np.random.randint(5,10,3)


array([7, 5, 7], dtype=int32)

In [ ]:

ran= np.random.randint(5,10,3)
ran

array([5, 8, 9], dtype=int32)

In [ ]:
otp=np.random.randint(5,10,4)
print(otp)

[7 5 9 5]


In [ ]:
arr1=np.random.randint(10,40,(10,10))              # 10 X 10 matrix , value interval between 10to 39
print(arr1)

[[31 21 17 18 12 22 30 37 23 25]
 [20 25 30 38 22 38 30 16 23 11]
 [23 36 10 33 17 13 10 13 13 17]
 [20 30 34 35 28 33 32 11 25 19]
 [13 29 33 39 36 28 16 20 34 11]
 [34 31 17 27 26 15 32 20 33 16]
 [19 38 38 31 39 25 31 11 29 33]
 [32 27 31 13 36 13 22 31 37 34]
 [38 11 28 25 35 18 37 13 38 33]
 [14 10 36 22 16 34 15 38 24 35]]


In [ ]:
arr1

array([[21, 24, 31, 38, 26, 15, 21, 16, 12, 24],
       [21, 38, 37, 37, 10, 35, 10, 12, 30, 31],
       [26, 32, 31, 30, 29, 36, 18, 10, 23, 19],
       [31, 11, 18, 18, 16, 13, 31, 14, 25, 18],
       [27, 13, 10, 38, 20, 18, 38, 20, 38, 15],
       [29, 35, 29, 10, 18, 12, 31, 27, 39, 28],
       [33, 37, 37, 36, 18, 33, 21, 19, 25, 21],
       [10, 25, 36, 22, 16, 11, 17, 35, 29, 22],
       [25, 30, 29, 23, 18, 12, 15, 32, 34, 22],
       [35, 37, 19, 25, 34, 34, 36, 37, 25, 37]], dtype=int32)

In [48]:
arr2=np.random.randint(1,5,(3,3))
arr2

array([[1, 3, 3],
       [2, 3, 1],
       [3, 1, 3]], dtype=int32)

## indexing, slicing in array

In [ ]:
arr2[:]

array([[3, 1, 3],
       [3, 2, 1],
       [4, 2, 3]], dtype=int32)

In [ ]:
len(arr2)

3

In [ ]:
arr2.shape

(3, 3)

In [ ]:
arr1.shape


(10, 10)

In [ ]:
len(arr1)

10

In [ ]:
arr1.shape


(10, 10)

In [ ]:
arr2

array([[3, 1, 3],
       [3, 2, 1],
       [4, 2, 3]], dtype=int32)

In [ ]:
arr2[0]

array([3, 1, 3], dtype=int32)

In [ ]:
arr2[1] 


array([3, 2, 1], dtype=int32)

In [ ]:
arr2

array([[3, 1, 3],
       [3, 2, 1],
       [4, 2, 3]], dtype=int32)

In [ ]:
arr2[:,1]


array([1, 2, 2], dtype=int32)

In [ ]:
arr2[:,2]


array([3, 1, 3], dtype=int32)

In [ ]:
arr2

array([[3, 1, 3],
       [3, 2, 1],
       [4, 2, 3]], dtype=int32)

In [ ]:
arr2[0]


array([3, 1, 3], dtype=int32)

In [ ]:
v = arr2[1, 2]
print(v)

1


In [ ]:
arr1

array([[21, 24, 31, 38, 26, 15, 21, 16, 12, 24],
       [21, 38, 37, 37, 10, 35, 10, 12, 30, 31],
       [26, 32, 31, 30, 29, 36, 18, 10, 23, 19],
       [31, 11, 18, 18, 16, 13, 31, 14, 25, 18],
       [27, 13, 10, 38, 20, 18, 38, 20, 38, 15],
       [29, 35, 29, 10, 18, 12, 31, 27, 39, 28],
       [33, 37, 37, 36, 18, 33, 21, 19, 25, 21],
       [10, 25, 36, 22, 16, 11, 17, 35, 29, 22],
       [25, 30, 29, 23, 18, 12, 15, 32, 34, 22],
       [35, 37, 19, 25, 34, 34, 36, 37, 25, 37]], dtype=int32)

In [ ]:
arr1[-7]

array([31, 11, 18, 18, 16, 13, 31, 14, 25, 18], dtype=int32)

In [ ]:
arr1[:,-7]

array([38, 37, 30, 18, 38, 10, 36, 22, 23, 25], dtype=int32)

In [ ]:
arr1

array([[21, 24, 31, 38, 26, 15, 21, 16, 12, 24],
       [21, 38, 37, 37, 10, 35, 10, 12, 30, 31],
       [26, 32, 31, 30, 29, 36, 18, 10, 23, 19],
       [31, 11, 18, 18, 16, 13, 31, 14, 25, 18],
       [27, 13, 10, 38, 20, 18, 38, 20, 38, 15],
       [29, 35, 29, 10, 18, 12, 31, 27, 39, 28],
       [33, 37, 37, 36, 18, 33, 21, 19, 25, 21],
       [10, 25, 36, 22, 16, 11, 17, 35, 29, 22],
       [25, 30, 29, 23, 18, 12, 15, 32, 34, 22],
       [35, 37, 19, 25, 34, 34, 36, 37, 25, 37]], dtype=int32)

In [ ]:
arr1[3:4, 2:6]


array([[18, 18, 16, 13]], dtype=int32)

In [ ]:
arr2

array([[3, 1, 3],
       [3, 2, 1],
       [4, 2, 3]], dtype=int32)

In [ ]:
arr2[1]

array([3, 2, 1], dtype=int32)

In [ ]:
arr2[1,2]

np.int32(1)

In [ ]:
arr2

array([[3, 1, 3],
       [3, 2, 1],
       [4, 2, 3]], dtype=int32)

In [ ]:
arr2[1:2]


array([[3, 2, 1]], dtype=int32)

In [ ]:
print(arr1)

[[31 21 17 18 12 22 30 37 23 25]
 [20 25 30 38 22 38 30 16 23 11]
 [23 36 10 33 17 13 10 13 13 17]
 [20 30 34 35 28 33 32 11 25 19]
 [13 29 33 39 36 28 16 20 34 11]
 [34 31 17 27 26 15 32 20 33 16]
 [19 38 38 31 39 25 31 11 29 33]
 [32 27 31 13 36 13 22 31 37 34]
 [38 11 28 25 35 18 37 13 38 33]
 [14 10 36 22 16 34 15 38 24 35]]


In [49]:
print(arr2)


[[1 3 3]
 [2 3 1]
 [3 1 3]]


In [43]:
arr1[0:10:5]

array([[31, 21, 17, 18, 12, 22, 30, 37, 23, 25],
       [34, 31, 17, 27, 26, 15, 32, 20, 33, 16]], dtype=int32)

In [44]:
arr1[::-1]

array([[14, 10, 36, 22, 16, 34, 15, 38, 24, 35],
       [38, 11, 28, 25, 35, 18, 37, 13, 38, 33],
       [32, 27, 31, 13, 36, 13, 22, 31, 37, 34],
       [19, 38, 38, 31, 39, 25, 31, 11, 29, 33],
       [34, 31, 17, 27, 26, 15, 32, 20, 33, 16],
       [13, 29, 33, 39, 36, 28, 16, 20, 34, 11],
       [20, 30, 34, 35, 28, 33, 32, 11, 25, 19],
       [23, 36, 10, 33, 17, 13, 10, 13, 13, 17],
       [20, 25, 30, 38, 22, 38, 30, 16, 23, 11],
       [31, 21, 17, 18, 12, 22, 30, 37, 23, 25]], dtype=int32)

In [45]:
arr1[::-2]


array([[14, 10, 36, 22, 16, 34, 15, 38, 24, 35],
       [32, 27, 31, 13, 36, 13, 22, 31, 37, 34],
       [34, 31, 17, 27, 26, 15, 32, 20, 33, 16],
       [20, 30, 34, 35, 28, 33, 32, 11, 25, 19],
       [20, 25, 30, 38, 22, 38, 30, 16, 23, 11]], dtype=int32)

In [50]:
arr2

array([[1, 3, 3],
       [2, 3, 1],
       [3, 1, 3]], dtype=int32)