In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print('Array a:',a)

Array a: [1 2 3]


In [3]:
b=np.arange(0,10,2)
print('Array b:',b)


Array b: [0 2 4 6 8]


In [4]:
d=np.zeros((2,3))
print('Array d:\n',d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
e=np.ones((3,2), dtype=int)
print('array e:\n',e)

array e:
 [[1 1]
 [1 1]
 [1 1]]


In [8]:
f=np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 2. Array Manipulation Functions

In [9]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1, (3,1))
print('Reshapd array',reshaped)

Reshapd array [[1]
 [2]
 [3]]


In [10]:
f1=np.array([[1,2],[3,4]])
flattened=np.ravel(f1)
print("Flattened arrray", flattened)

Flattened arrray [1 2 3 4]


In [11]:
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1)
print("Transposed arrray:\n", transposed)


Transposed arrray:
 [[1 3]
 [2 4]]


In [12]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [13]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [1 2 3 4]
