In [1]:
import numpy as np

In [3]:
arr=[0,1,2,3,4,5]

In [5]:
arr=np.array(arr)

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
arr.reshape(6,1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
arr.reshape(1,6)


array([[0, 1, 2, 3, 4, 5]])

In [11]:
arr1=np.random.randint(1,5,(3,3))
arr1

array([[1, 2, 3],
       [2, 3, 4],
       [3, 3, 1]], dtype=int32)

In [12]:
arr1[0:2,1:3]

array([[2, 3],
       [3, 4]], dtype=int32)

In [13]:
arr0=np.random.randint(10,40,(10,10))              # 10 X 10 matrix , value interval between 10to 39
print(arr0)

[[36 27 31 35 34 24 23 29 16 15]
 [17 11 12 22 29 21 39 33 11 19]
 [12 24 37 24 24 16 36 15 21 38]
 [11 37 33 11 21 22 11 28 33 34]
 [33 13 14 22 26 15 12 37 35 33]
 [12 34 20 24 23 33 18 21 26 12]
 [31 29 23 32 37 23 25 31 34 29]
 [23 30 33 22 32 37 10 38 34 29]
 [13 36 26 17 24 17 30 30 35 13]
 [37 31 34 22 23 17 30 25 36 33]]


In [14]:
arr0< 20

array([[False, False, False, False, False, False, False, False,  True,
         True],
       [ True,  True,  True, False, False, False, False, False,  True,
         True],
       [ True, False, False, False, False,  True, False,  True, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
        False],
       [False,  True,  True, False, False,  True,  True, False, False,
        False],
       [ True, False, False, False, False, False,  True, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [ True, False, False,  True, False,  True, False, False, False,
         True],
       [False, False, False, False, False,  True, False, False, False,
        False]])

In [15]:
arr0

array([[36, 27, 31, 35, 34, 24, 23, 29, 16, 15],
       [17, 11, 12, 22, 29, 21, 39, 33, 11, 19],
       [12, 24, 37, 24, 24, 16, 36, 15, 21, 38],
       [11, 37, 33, 11, 21, 22, 11, 28, 33, 34],
       [33, 13, 14, 22, 26, 15, 12, 37, 35, 33],
       [12, 34, 20, 24, 23, 33, 18, 21, 26, 12],
       [31, 29, 23, 32, 37, 23, 25, 31, 34, 29],
       [23, 30, 33, 22, 32, 37, 10, 38, 34, 29],
       [13, 36, 26, 17, 24, 17, 30, 30, 35, 13],
       [37, 31, 34, 22, 23, 17, 30, 25, 36, 33]], dtype=int32)

In [16]:
arr0[arr0<20]

array([16, 15, 17, 11, 12, 11, 19, 12, 16, 15, 11, 11, 11, 13, 14, 15, 12,
       12, 18, 12, 10, 13, 17, 17, 13, 17], dtype=int32)

In [17]:
arr0[arr0==20]

array([20], dtype=int32)

In [18]:
arr0[arr0!=20]


array([36, 27, 31, 35, 34, 24, 23, 29, 16, 15, 17, 11, 12, 22, 29, 21, 39,
       33, 11, 19, 12, 24, 37, 24, 24, 16, 36, 15, 21, 38, 11, 37, 33, 11,
       21, 22, 11, 28, 33, 34, 33, 13, 14, 22, 26, 15, 12, 37, 35, 33, 12,
       34, 24, 23, 33, 18, 21, 26, 12, 31, 29, 23, 32, 37, 23, 25, 31, 34,
       29, 23, 30, 33, 22, 32, 37, 10, 38, 34, 29, 13, 36, 26, 17, 24, 17,
       30, 30, 35, 13, 37, 31, 34, 22, 23, 17, 30, 25, 36, 33],
      dtype=int32)

In [19]:
arr0[arr0>=20]


array([36, 27, 31, 35, 34, 24, 23, 29, 22, 29, 21, 39, 33, 24, 37, 24, 24,
       36, 21, 38, 37, 33, 21, 22, 28, 33, 34, 33, 22, 26, 37, 35, 33, 34,
       20, 24, 23, 33, 21, 26, 31, 29, 23, 32, 37, 23, 25, 31, 34, 29, 23,
       30, 33, 22, 32, 37, 38, 34, 29, 36, 26, 24, 30, 30, 35, 37, 31, 34,
       22, 23, 30, 25, 36, 33], dtype=int32)

In [21]:
arr0[arr0>35]


array([36, 39, 37, 36, 38, 37, 37, 37, 37, 38, 36, 37, 36], dtype=int32)

In [22]:
arr

array([0, 1, 2, 3, 4, 5])

In [23]:
max(arr)

np.int64(5)

In [24]:
min(arr)

np.int64(0)

### POC: Proof of Concept
### Image to array